//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Currency_exchanger.Mod
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public int lid { get; set; }
        public string login1 { get; set; }
        public string pass { get; set; }
    }
}
